# Generated by Django 5.0.3 on 2024-03-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(db_comment='[PK]', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ManifestDate',
            fields=[
                ('id', models.AutoField(db_comment='[PK]', primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(db_comment='[PK]', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('storage_type', models.CharField(max_length=100)),
                ('levels', models.CharField(max_length=100)),
                ('iid', models.IntegerField()),
                ('available_interval_begin', models.TimeField()),
                ('available_interval_end', models.TimeField()),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to='data_processor.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='exchange',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='data_processor.manifestdate'),
        ),
    ]
